name: CI/CD

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: cd dapp && npm install

    - name: Build
      run: cd dapp && npm run build
      env:
        REACT_APP_WEB3_ADDRESS: 'https://data-seed-prebsc-1-s1.binance.org:8545'
        REACT_APP_USE_HASH_ROUTER: true

    - name: Deploy
      run: |
        cd dapp
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/henft-game/henft-game.github.io.git
        npm run deploy
      env:
        REACT_APP_WEB3_ADDRESS: 'https://data-seed-prebsc-1-s1.binance.org:8545'
        REACT_APP_USE_HASH_ROUTER: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
